"""Spec Generator: Spec Kit + BMAD hybrid.

Generates hyper-detailed, agent-ready specs with launch commands for IDEs.
"""

from __future__ import annotations

import json
import re
from datetime import date
from pathlib import Path
from typing import Any

from engine.store.db import init_db
from engine.providers import complete, get_provider
from engine.store import write_spec


SPEC_TEMPLATE = """# {title}

> {summary}

## Metadata
- **Idea ID**: {idea_id}
- **Date**: {date}
- **Viability Score**: {viability_score}/100 (confidence: {viability_confidence}%)
- **Status**: {status}
- **Origin**: {origin}
- **Tags**: {tags}

{body}

## Launch Commands (Copy to IDE)

### Claude Code
```bash
claude -p "$(cat SPEC.md)"
```

### OpenCode
```bash
opencode run "$(cat SPEC.md)"
```

### Codex CLI
```bash
codex exec "$(cat SPEC.md)"
```

### Cursor
```bash
cursor agent -p "$(cat SPEC.md)"
```

### Antigravity
```bash
antigravity run "$(cat SPEC.md)"
```

---
*Generated by Daily Vibe Coding Engine — {date}*
"""


def load_idea(conn, idea_id: int) -> dict | None:
    row = conn.execute("SELECT * FROM ideas WHERE id = ?", (idea_id,)).fetchone()
    if not row:
        return None
    idea = dict(row)
    idea["viability"] = json.loads(idea["viability"]) if idea.get("viability") else {}
    tag_rows = conn.execute("""
        SELECT DISTINCT t.name FROM tags t
        JOIN item_tags it ON it.tag_id = t.id
        JOIN items i ON i.id = it.item_id
        WHERE i.id = ? OR (? IS NULL AND i.url = ?)
    """, (idea.get("item_id"), idea.get("item_id"), idea.get("source_url") or "")).fetchall()
    idea["tags"] = [r["name"] for r in tag_rows]
    return idea


def load_cluster_items(conn, idea_id: int) -> list[dict]:
    rows = conn.execute("""
        SELECT DISTINCT i.*, s.name as source_name
        FROM ideas ide
        JOIN items i ON i.id = ide.item_id
            OR (ide.item_id IS NULL AND i.url = ide.source_url)
        JOIN item_clusters ic ON ic.item_id = i.id
        JOIN clusters c ON ic.cluster_id = c.id
        JOIN sources s ON i.source_id = s.id
        WHERE ide.id = ?
    """, (idea_id,)).fetchall()
    return [dict(r) for r in rows]


def _clamp_title(title: str, limit: int = 70) -> str:
    if len(title) <= limit:
        return title
    return title[:limit - 3].rstrip() + "..."


FALLBACK_MARKER = "<!-- spec-generation-failed -->"

SPEC_SECTIONS: tuple[tuple[str, str], ...] = (
    ("problem", "Problem"),
    ("solution", "Solution"),
    ("target_user", "Target User"),
    ("features", "Key Features"),
    ("tech_stack", "Tech Stack & Architecture"),
    ("data_model", "Data Model"),
    ("api", "API / Interfaces"),
    ("ui_ux", "UI/UX Requirements"),
    ("monetization", "Monetization"),
    ("risks", "Risks & Mitigation"),
    ("launch_checklist", "Launch Checklist"),
    ("cited_sources", "Cited Sources"),
)

# Sections are requested in separate calls. Measured 2026-09-27 on
# nvidia/nemotron-3-ultra-550b-a55b:free (tools/diagnose_truncation.py): all 12
# sections in one request wants >9.7k completion tokens and still fails to
# parse, whether it truncates (finish_reason=length) or not. Four sections
# finish naturally at ~2.3k tokens and parse reliably. Smaller groups also
# mean a lost call costs 4 sections instead of all 12.
MAX_SECTIONS_PER_CALL = 4

# A group that comes back truncated (measured: JSON escaping burns tokens, so a
# 4-section group overruns a 2000-token cap) or that answers only some of its
# keys is re-asked, narrowed to whatever is still missing. Bounded so a group
# that never succeeds cannot spin.
MAX_GROUP_ATTEMPTS = 2

SPEC_GROUPS: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("Problem and value", ("problem", "solution", "target_user", "features")),
    # Measured 2026-09-27: the four architecture sections as one group were
    # still truncated at max_tokens=3200, twice in a row, because tech_stack
    # and api make the model emit large code blocks. Two sections each fit.
    ("Stack and data", ("tech_stack", "data_model")),
    ("Interfaces and UX", ("api", "ui_ux")),
    ("Shipping", ("monetization", "risks", "launch_checklist", "cited_sources")),
)


def extract_json_object(text: str) -> dict | None:
    """Достаёт JSON-объект из ответа модели.

    Модели любят оборачивать JSON в ```json-блок, добавлять прозу
    до/после и ломать формат. Здесь снимаем все эти обёртки, прежде чем
    сдаваться на fallback.
    """
    if not text:
        return None
    candidate = text.strip()

    fence = re.search(
        r"```(?:json)?\s*(.+?)\s*```", candidate, re.DOTALL | re.IGNORECASE
    )
    if fence:
        candidate = fence.group(1).strip()

    try:
        parsed = json.loads(candidate)
        if isinstance(parsed, dict):
            return parsed
    except json.JSONDecodeError:
        pass

    start = candidate.find("{")
    if start == -1:
        return None
    depth = 0
    in_string = False
    escaped = False
    for idx in range(start, len(candidate)):
        char = candidate[idx]
        if in_string:
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == '"':
                in_string = False
            continue
        if char == '"':
            in_string = True
        elif char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                try:
                    parsed = json.loads(candidate[start : idx + 1])
                except json.JSONDecodeError:
                    return None
                return parsed if isinstance(parsed, dict) else None
    return None


def generate_spec(idea: dict, cluster_items: list[dict]) -> str:
    viability = idea.get("viability", {})
    source_items = []
    for item in cluster_items[:15]:
        meta = json.loads(item.get("meta", "{}")) if item.get("meta") else {}
        source_items.append({
            "title": item["title"],
            "url": item["url"],
            "description": item["description"][:300] if item.get("description") else "",
            "source": item.get("source_name", ""),
            "meta": meta,
        })

    prompt_head = f"""Generate a HYPER-DETAILED, AGENT-READY SPEC for this idea.

## Idea
**Title**: {idea['title']}
**Summary**: {idea.get('summary', '')}
**Viability**: {json.dumps(viability, ensure_ascii=False)}
**Tags**: {', '.join(idea.get('tags', []))}

## Source Materials (cite as [source:N])
{json.dumps(source_items, ensure_ascii=False, indent=2)}
"""

    style = (
        "Style: Spec Kit constitution structure + BMAD role depth "
        "(Analyst/PM/Architect/Dev/QA). No fluff. MVP scope 2-4 weeks.\n"
        "Return ONLY a JSON object, no prose before or after it."
    )

    grounding = (
        "Grounding rules:\n"
        "- Use ONLY the source materials above. Never invent statistics, dates, "
        "quotes, versions, or URLs.\n"
        "- If the sources do not support a claim, write that it is unknown "
        "instead of guessing.\n"
        "- Every factual claim cites a source as [source:N].\n"
        "- cited_sources must list only URLs that appear in the source materials."
    )

    collected: dict[str, str] = {}
    failures: list[str] = []

    for group_name, keys in SPEC_GROUPS:
        outstanding = list(keys)
        for attempt in range(MAX_GROUP_ATTEMPTS):
            if not outstanding:
                break
            requested = {
                key: f"## {heading}\\n\\n..."
                for key, heading in SPEC_SECTIONS
                if key in outstanding
            }
            # A retry must be a *different request*, not a replay. Measured
            # 2026-09-27: 30 of 85 cached responses were truncated, and
            # because the cache served them back verbatim, every retry got the
            # identical broken text and a group could never recover. The
            # attempt marker changes the prompt, and cache=False keeps the
            # answer out of the cache so a bad one cannot be replayed later.
            retry_note = (
                ""
                if attempt == 0
                else (
                    f"\nThis is attempt {attempt + 1}. Your previous answer was "
                    f"cut off before the JSON closed. Be markedly shorter this "
                    f"time: drop code blocks, keep each section under 120 "
                    f"words, and make sure the final }} is present.\n"
                )
            )
            prompt = (
                f"{prompt_head}\n"
                f"## Task\n"
                f"Write ONLY these sections of the spec: {group_name}.\n"
                f"{retry_note}\n"
                f"## Required Output Format\n"
                f"Return ONLY a JSON object with exactly these keys and no "
                f"others: "
                f"{', '.join(requested)}.\n"
                f"Every key must be present. The JSON must be complete and "
                f"closed.\n\n"
                f"Example shape:\n"
                f"{json.dumps(requested, indent=2, ensure_ascii=False)}\n\n"
                f"Keep each section concise so the whole object fits in the "
                f"response limit.\n"
                f"{style}\n"
                f"{grounding}"
            )
            try:
                response = complete(prompt, stage="expensive", cache=False)
            except Exception as exc:  # noqa: BLE001
                failures.append(f"{group_name}: {exc}")
                break
            payload = extract_json_object(response.content)
            if not payload:
                # Truncated or malformed: nothing recovered, so re-ask the
                # whole outstanding set rather than silently dropping it.
                failures.append(f"{group_name}: unparseable response (attempt {attempt + 1})")
                continue
            still_missing: list[str] = []
            for key in outstanding:
                value = str(payload.get(key, "")).strip()
                if value:
                    collected[key] = value
                else:
                    still_missing.append(key)
            outstanding = still_missing

        if outstanding:
            failures.append(
                f"{group_name}: no content for {', '.join(outstanding)}"
            )

    if not collected:
        reasons = "; ".join(failures) if failures else "no sections returned"
        body = (
            f"{FALLBACK_MARKER}\n\n"
            "> **This spec was not generated.** No section could be produced, so "
            "nothing below is filled in. Nothing here may be published or treated "
            f"as analysis. Cause: {reasons}"
        )
    else:
        body = "\n\n".join(
            collected.get(key, "").strip() or f"## {heading}\n\n(not provided by model)"
            for key, heading in SPEC_SECTIONS
        )
        if failures:
            body += (
                "\n\n> *Partial spec: "
                + "; ".join(failures)
                + ". Sections that failed are marked above.*"
            )

    return SPEC_TEMPLATE.format(
        title=_clamp_title(idea["title"]),
        summary=idea.get("summary", ""),
        idea_id=idea["id"],
        date=date.today().isoformat(),
        viability_score=viability.get("score", 0),
        viability_confidence=viability.get("confidence", 0),
        status=idea.get("status", "draft"),
        origin=idea.get("origin", "research"),
        tags=", ".join(idea.get("tags", [])),
        body=body,
    )


INCOMPLETE_MARKER = "(not provided by model)"


def spec_is_incomplete(spec_path: str | Path) -> bool:
    """True when a stored spec still has sections the model never filled in.

    The `specs` table records only a path, so completeness is a property of the
    file. The pipeline and the repair tooling must agree on the definition, or
    the tool can report a spec as clean while the pipeline keeps skipping it.
    """
    path = Path(spec_path)
    if not path.exists():
        return True
    text = path.read_text(encoding="utf-8", errors="replace")
    return FALLBACK_MARKER in text or INCOMPLETE_MARKER in text


def select_ideas_needing_specs(conn) -> list[int]:
    """Ideas that have no spec, or whose spec is missing/incomplete on disk.

    Selecting only `specs.id IS NULL` made a partial spec permanent: the row
    existed, so the idea was never retried, and the artifact stayed broken
    forever with no way for the pipeline to heal it.
    """
    rows = conn.execute("""
        SELECT i.id AS id, s.path AS spec_path
        FROM ideas i
        LEFT JOIN specs s ON i.id = s.idea_id
        WHERE i.status IN ('new', 'watching', 'spec')
        ORDER BY i.id
    """).fetchall()
    return [
        row["id"]
        for row in rows
        if not row["spec_path"] or spec_is_incomplete(row["spec_path"])
    ]


def save_spec(conn, idea_id: int, spec_path: str) -> int:
    # Regeneration is routine now that incomplete specs are retried, so the
    # write must be idempotent: one row per idea, not one per attempt.
    conn.execute("DELETE FROM specs WHERE idea_id = ?", (idea_id,))
    cur = conn.execute(
        "INSERT INTO specs (idea_id, path, status, created_at) VALUES (?, ?, 'draft', datetime('now'))",
        (idea_id, spec_path),
    )
    conn.commit()
    return cur.lastrowid


def run_spec_generation(config: dict, idea_ids: list[int] | None = None) -> dict:
    conn = init_db()

    if idea_ids is None:
        idea_ids = select_ideas_needing_specs(conn)

    if not idea_ids:
        return {"specs": 0, "message": "No ideas to spec"}

    results = []
    errors = []
    skipped_budget = False
    for idea_id in idea_ids:
        from engine.providers import get_provider

        registry = get_provider(config)
        if registry.budget_exhausted("spec"):
            skipped_budget = True
            break
        idea = load_idea(conn, idea_id)
        if not idea:
            continue
        try:
            cluster_items = load_cluster_items(conn, idea_id)
            spec_md = generate_spec(idea, cluster_items)
        except Exception as exc:  # noqa: BLE001
            errors.append({"idea_id": idea_id, "error": str(exc)[:300]})
            continue
        spec_path = write_spec(
            idea_id, idea["title"], spec_md,
            idea.get("viability", {}), tags=idea.get("tags", []),
            description=idea.get("summary", ""),
        )
        save_spec(conn, idea_id, str(spec_path))
        conn.execute("UPDATE ideas SET status = 'spec' WHERE id = ?", (idea_id,))
        conn.commit()
        results.append({"idea_id": idea_id, "spec_path": str(spec_path)})

    out: dict = {"specs": len(results), "details": results}
    if errors:
        out["errors"] = errors
    if skipped_budget:
        out["skipped_budget"] = True
    return out