"""Spec Generator: Spec Kit + BMAD hybrid.

Generates hyper-detailed, agent-ready specs with launch commands for IDEs.
"""

from __future__ import annotations

import json
from datetime import date
from pathlib import Path
from typing import Any

from engine.store.db import init_db
from engine.providers import complete, get_provider
from engine.store import write_spec


SPEC_TEMPLATE = """# {title}

> {summary}

## Metadata
- **Idea ID**: {idea_id}
- **Date**: {date}
- **Viability Score**: {viability_score}/100 (confidence: {viability_confidence}%)
- **Status**: {status}
- **Origin**: {origin}
- **Tags**: {tags}

{body}

## Launch Commands (Copy to IDE)

### Claude Code
```bash
claude -p "$(cat SPEC.md)"
```

### OpenCode
```bash
opencode run "$(cat SPEC.md)"
```

### Codex CLI
```bash
codex exec "$(cat SPEC.md)"
```

### Cursor
```bash
cursor agent -p "$(cat SPEC.md)"
```

### Antigravity
```bash
antigravity run "$(cat SPEC.md)"
```

---
*Generated by Daily Vibe Coding Engine — {date}*
"""


def load_idea(conn, idea_id: int) -> dict | None:
    row = conn.execute("SELECT * FROM ideas WHERE id = ?", (idea_id,)).fetchone()
    if not row:
        return None
    idea = dict(row)
    idea["viability"] = json.loads(idea["viability"]) if idea.get("viability") else {}
    tag_rows = conn.execute("""
        SELECT DISTINCT t.name FROM tags t
        JOIN item_tags it ON it.tag_id = t.id
        JOIN items i ON i.id = it.item_id
        WHERE i.id = ? OR (? IS NULL AND i.url = ?)
    """, (idea.get("item_id"), idea.get("item_id"), idea.get("source_url") or "")).fetchall()
    idea["tags"] = [r["name"] for r in tag_rows]
    return idea


def load_cluster_items(conn, idea_id: int) -> list[dict]:
    rows = conn.execute("""
        SELECT DISTINCT i.*, s.name as source_name
        FROM ideas ide
        JOIN items i ON i.id = ide.item_id
            OR (ide.item_id IS NULL AND i.url = ide.source_url)
        JOIN item_clusters ic ON ic.item_id = i.id
        JOIN clusters c ON ic.cluster_id = c.id
        JOIN sources s ON i.source_id = s.id
        WHERE ide.id = ?
    """, (idea_id,)).fetchall()
    return [dict(r) for r in rows]


def _clamp_title(title: str, limit: int = 70) -> str:
    if len(title) <= limit:
        return title
    return title[:limit - 3].rstrip() + "..."


def generate_spec(idea: dict, cluster_items: list[dict]) -> str:
    viability = idea.get("viability", {})
    source_items = []
    for item in cluster_items[:15]:
        meta = json.loads(item.get("meta", "{}")) if item.get("meta") else {}
        source_items.append({
            "title": item["title"],
            "url": item["url"],
            "description": item["description"][:300] if item.get("description") else "",
            "source": item.get("source_name", ""),
            "meta": meta,
        })

    prompt = f"""Generate a HYPER-DETAILED, AGENT-READY SPEC for this idea.

## Idea
**Title**: {idea['title']}
**Summary**: {idea.get('summary', '')}
**Viability**: {json.dumps(viability, ensure_ascii=False)}
**Tags**: {', '.join(idea.get('tags', []))}

## Source Materials (cite as [source:N])
{json.dumps(source_items, ensure_ascii=False, indent=2)}

## Required Output Format
Return ONLY a JSON object with these Markdown string fields:

{{
  "problem": "## Problem\\n\\nDetailed problem statement...",
  "solution": "## Solution\\n\\nExact solution...",
  "target_user": "## Target User\\n\\nPrimary persona...",
  "features": "## Key Features\\n\\n1. **Feature** — description (P0/P1/P2)",
  "tech_stack": "## Tech Stack & Architecture\\n\\nRecommended stack...",
  "data_model": "## Data Model\\n\\nCore entities...",
  "api": "## API / Interfaces\\n\\nKey endpoints...",
  "ui_ux": "## UI/UX Requirements\\n\\nKey screens...",
  "monetization": "## Monetization\\n\\nPricing model...",
  "risks": "## Risks & Mitigation\\n\\n| Risk | Likelihood | Impact | Mitigation |...",
  "launch_checklist": "## Launch Checklist\\n\\n1. [ ] Pre-launch...",
  "cited_sources": "## Cited Sources\\n\\n[1] Title — URL"
}}

Style: Spec Kit constitution structure + BMAD role depth (Analyst/PM/Architect/Dev/QA).
Every claim from sources → [source:N]. No fluff. MVP scope 2-4 weeks."""

    response = complete(prompt, stage="expensive")
    try:
        spec_data = json.loads(response.content)
    except json.JSONDecodeError:
        spec_data = _fallback_spec(idea)

    body = "\n\n".join([
        spec_data.get("problem", "## Problem\n\nTBD"),
        spec_data.get("solution", "## Solution\n\nTBD"),
        spec_data.get("target_user", "## Target User\n\nTBD"),
        spec_data.get("features", "## Key Features\n\nTBD"),
        spec_data.get("tech_stack", "## Tech Stack & Architecture\n\nTBD"),
        spec_data.get("data_model", "## Data Model\n\nTBD"),
        spec_data.get("api", "## API / Interfaces\n\nTBD"),
        spec_data.get("ui_ux", "## UI/UX Requirements\n\nTBD"),
        spec_data.get("monetization", "## Monetization\n\nTBD"),
        spec_data.get("risks", "## Risks & Mitigation\n\nTBD"),
        spec_data.get("launch_checklist", "## Launch Checklist\n\nTBD"),
        spec_data.get("cited_sources", "## Cited Sources\n\nTBD"),
    ])

    return SPEC_TEMPLATE.format(
        title=_clamp_title(idea["title"]),
        summary=idea.get("summary", ""),
        idea_id=idea["id"],
        date=date.today().isoformat(),
        viability_score=viability.get("score", 0),
        viability_confidence=viability.get("confidence", 0),
        status=idea.get("status", "draft"),
        origin=idea.get("origin", "research"),
        tags=", ".join(idea.get("tags", [])),
        body=body,
    )


def _fallback_spec(idea: dict) -> dict:
    s = idea.get("summary", "")
    return {
        "problem": f"## Problem\n\n{s}",
        "solution": "## Solution\n\nSee summary above.",
        "target_user": "## Target User\n\nDevelopers and builders.",
        "features": "## Key Features\n\n1. Core feature (P0)",
        "tech_stack": "## Tech Stack & Architecture\n\nPython + SQLite + Markdown.",
        "data_model": "## Data Model\n\nSee plan.md.",
        "api": "## API / Interfaces\n\nREST API.",
        "ui_ux": "## UI/UX Requirements\n\nClean, fast, accessible.",
        "monetization": "## Monetization\n\nFreemium.",
        "risks": "## Risks & Mitigation\n\n| Risk | L | I | M |\n|---|---|---|---|\n| Market | M | M | Validate early |",
        "launch_checklist": "## Launch Checklist\n\n1. [ ] Build MVP\n2. [ ] Test\n3. [ ] Launch",
        "cited_sources": "## Cited Sources\n\nGenerated from fetched items.",
    }


def save_spec(conn, idea_id: int, spec_path: str) -> int:
    cur = conn.execute(
        "INSERT INTO specs (idea_id, path, status, created_at) VALUES (?, ?, 'draft', datetime('now'))",
        (idea_id, spec_path),
    )
    conn.commit()
    return cur.lastrowid


def run_spec_generation(config: dict, idea_ids: list[int] | None = None) -> dict:
    conn = init_db()

    if idea_ids is None:
        rows = conn.execute("""
            SELECT i.id FROM ideas i
            LEFT JOIN specs s ON i.id = s.idea_id
            WHERE i.status IN ('new', 'watching') AND s.id IS NULL
        """).fetchall()
        idea_ids = [r["id"] for r in rows]

    if not idea_ids:
        return {"specs": 0, "message": "No ideas to spec"}

    results = []
    for idea_id in idea_ids:
        idea = load_idea(conn, idea_id)
        if not idea:
            continue
        cluster_items = load_cluster_items(conn, idea_id)
        spec_md = generate_spec(idea, cluster_items)
        spec_path = write_spec(
            idea_id, idea["title"], spec_md,
            idea.get("viability", {}), tags=idea.get("tags", []),
            description=idea.get("summary", ""),
        )
        save_spec(conn, idea_id, str(spec_path))
        conn.execute("UPDATE ideas SET status = 'spec' WHERE id = ?", (idea_id,))
        conn.commit()
        results.append({"idea_id": idea_id, "spec_path": str(spec_path)})

    return {"specs": len(results), "details": results}